default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: slavik

development:
  <<: *default
  database: assignment_1_dev

test:
  <<: *default
  database: assignment_1_test

production:
  url: <%= ENV['DATABASE_URL'] %>