development: &default
  host: <%= "https://#{ENV['ELASTIC_USER']}:#{ENV['ELASTIC_PASSWORD']}@localhost:9200" %>
  transport_options:
    request:
      timeout: !!integer 300
    ssl:
      ca_file: '/Users/slavik/Development/personal/Assignment_1/http_ca.crt'
test:
  <<: *default
staging:
  <<: *default
production:
  cloud_id: <%= ENV['ELASTIC_CLOUD_ID'] %>
  user: <%= ENV['ELASTIC_USER'] %>
  password: <%= ENV['ELASTIC_PASSWORD'] %>
  transport_options:
    request:
      timeout: !!integer 300